version: '3'
services:
  vsftpd:
    container_name: vsftpd
    image: "fauria/vsftpd"
    volumes:
      - ~/calibre/data:/home/vsftpd
    ports:
    - "20:20"
    - "21:21"
    - "21100-21110:21100-21110"
    environment:
    - FTP_USER=[user]
    - FTP_PASS=[passwd]
    - PASV_ADDRESS=127.0.0.1
    - PASV_MIN_PORT=21100
    - PASV_MAX_PORT=21110
  calibre:
    container_name: calibre
    image: "unicosmos/calibre"
    restart: always
    volumes:
      - ~/calibre/data/[user]:/data
